<a href="https://colab.research.google.com/github/AMJAMAITHILI/DL_LAB/blob/main/WEEK4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adadelta, Adam

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

model = Sequential([
    Dense(4, activation='relu', input_shape=(2,)),
    Dense(1, activation='sigmoid')
])

# 1 Batch GD
model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')
model.fit(X,y,epochs=10,batch_size=4)
print(model.predict(X))

# 2 Stochastic GD
model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')
model.fit(X,y,epochs=10,batch_size=1,verbose=0)
print(model.predict(X))

# 3 Mini Batch GD
model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')
model.fit(X,y,epochs=10,batch_size=2,verbose=0)
print(model.predict(X))

# SGD with Momentum
model.compile(optimizer=SGD(learning_rate=0.1, momentum=0.9), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# SGD with Nesterov
model.compile(optimizer=SGD(learning_rate=0.1, momentum=0.9, nesterov=True), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# Adagrad
model.compile(optimizer=Adagrad(learning_rate=0.1, epsilon=1e-7), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# RMSprop
model.compile(optimizer=RMSprop(learning_rate=0.001, rho=0.9), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# Adadelta
model.compile(optimizer=Adadelta(learning_rate=1.0, rho=0.95), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# Adam
model.compile(optimizer=Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - loss: 0.6346
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.6313
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.6280
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.6247
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.6215
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.6183
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.6152
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.6121
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.6091
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6061
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[[0.48592803]
 [0.5770058 ]
 [0.62639534]
 [0.5177604 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0.44907972]
 [0.60990745]
 [0.65185195]
 [0.44907972]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0.42802584]
 [0.6273952 ]
 [0.68947613]
 [0.42802584]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
[[0.37792957]
 [0.6815583 ]
 [0.758