<a href="https://colab.research.google.com/github/AMJAMAITHILI/DL_LAB/blob/main/WEEK4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adadelta, Adam

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

model = Sequential([
    Dense(4, activation='relu', input_shape=(2,)),
    Dense(1, activation='sigmoid')
])

# 1 Batch GD
model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')
model.fit(X,y,epochs=10,batch_size=4)
print(model.predict(X))

# 2 Stochastic GD
model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')
model.fit(X,y,epochs=10,batch_size=1,verbose=0)
print(model.predict(X))

# 3 Mini Batch GD
model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')
model.fit(X,y,epochs=10,batch_size=2,verbose=0)
print(model.predict(X))

# SGD with Momentum
model.compile(optimizer=SGD(learning_rate=0.1, momentum=0.9), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# SGD with Nesterov
model.compile(optimizer=SGD(learning_rate=0.1, momentum=0.9, nesterov=True), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# Adagrad
model.compile(optimizer=Adagrad(learning_rate=0.1, epsilon=1e-7), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# RMSprop
model.compile(optimizer=RMSprop(learning_rate=0.001, rho=0.9), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# Adadelta
model.compile(optimizer=Adadelta(learning_rate=1.0, rho=0.95), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

# Adam
model.compile(optimizer=Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999), loss='binary_crossentropy')
model.fit(X,y,epochs=10,verbose=0)
print(model.predict(X))

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - loss: 0.6346
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.6313
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.6280
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.6247
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.6215
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.6183
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.6152
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.6121
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.6091
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6061
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[[0.48592803]
 [0.5770058 ]
 [0.62639534]
 [0.5177604 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0.44907972]
 [0.60990745]
 [0.65185195]
 [0.44907972]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0.42802584]
 [0.6273952 ]
 [0.68947613]
 [0.42802584]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
[[0.37792957]
 [0.6815583 ]
 [0.758

In [ ]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adadelta, Adam

# Load dataset
data = load_breast_cancer()
X = data.data
y = data.target.reshape(-1,1)

# Normalize
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Model function
def create_model():
    model = Sequential([
        Dense(16, activation='relu', input_shape=(X.shape[1],)),
        Dense(8, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    return model

results = []

# 1 Batch GD
model = create_model()
model.compile(optimizer=SGD(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, batch_size=len(X), verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["Batch GD", len(X), loss, acc])

# 2 Stochastic GD
model = create_model()
model.compile(optimizer=SGD(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, batch_size=1, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["SGD", 1, loss, acc])

# 3 Mini-batch GD
model = create_model()
model.compile(optimizer=SGD(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, batch_size=32, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["Mini-batch GD", 32, loss, acc])

# SGD with Momentum
model = create_model()
model.compile(optimizer=SGD(learning_rate=0.01, momentum=0.9), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["Momentum", 32, loss, acc])#default batch size 32

# SGD with Nesterov
model = create_model()
model.compile(optimizer=SGD(learning_rate=0.01, momentum=0.9, nesterov=True), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["Nesterov", 32, loss, acc])

# Adagrad
model = create_model()
model.compile(optimizer=Adagrad(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["Adagrad", 32, loss, acc])

# RMSprop
model = create_model()
model.compile(optimizer=RMSprop(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["RMSprop", 32, loss, acc])

# Adadelta
model = create_model()
model.compile(optimizer=Adadelta(learning_rate=1.0), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["Adadelta", 32, loss, acc])

# Adam
model = create_model()
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
results.append(["Adam", 32, loss, acc])

# 🔹 Print Comparison Table
print("\nComparison Table:\n")
print("{:<15} {:<10} {:<15} {:<10}".format("Optimizer", "Batch", "Loss", "Accuracy"))
print("-"*55)

for r in results:
    print("{:<15} {:<10} {:<15.4f} {:<10.4f}".format(r[0], r[1], r[2], r[3]))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)



Comparison Table:

Optimizer       Batch      Loss            Accuracy  
-------------------------------------------------------
Batch GD        569        0.7062          0.4306    
SGD             1          0.0382          0.9895    
Mini-batch GD   32         0.1823          0.9525    
Momentum        32         0.0538          0.9842    
Nesterov        32         0.0565          0.9842    
Adagrad         32         0.1992          0.9279    
RMSprop         32         0.0979          0.9684    
Adadelta        32         0.0938          0.9754    
Adam            32         0.0943          0.9807    


In [2]:
pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 772.9 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 156.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 111.5 MB/s eta 0:00:00
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0


In [3]:
import numpy as np
import pandas as pd
import time

from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adadelta, Adam

# ======================
# 1. Load & preprocess
# ======================
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

X_train = X_train / 255.0
X_test = X_test / 255.0

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# ======================
# 2. MLP Model
# ======================
def create_mlp():
    model = Sequential([
        Flatten(input_shape=(32,32,3)),
        Dense(512, activation='relu'),
        Dense(256, activation='relu'),
        Dense(10, activation='softmax')
    ])
    return model

# ======================
# 3. Experiments Setup
# ======================
experiments = [
    ("Batch GD", SGD(learning_rate=0.01), len(X_train)),
    ("SGD", SGD(learning_rate=0.01), 1),
    ("Mini-Batch GD", SGD(learning_rate=0.01), 64),
    ("Momentum", SGD(learning_rate=0.01, momentum=0.9), 64),
    ("Nesterov", SGD(learning_rate=0.01, momentum=0.9, nesterov=True), 64),
    ("Adagrad", Adagrad(learning_rate=0.01), 64),
    ("RMSprop", RMSprop(learning_rate=0.001), 64),
    ("Adadelta", Adadelta(), 64),
    ("Adam", Adam(learning_rate=0.001), 64),
]

results = []

# ======================
# 4. Training Loop
# ======================
for name, optimizer, batch_size in experiments:
    print(f"\nRunning: {name}")

    model = create_mlp()
    model.compile(
        optimizer=optimizer,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    start = time.time()

    history = model.fit(
        X_train, y_train,
        epochs=5,                  # increase for better results
        batch_size=batch_size,
        validation_data=(X_test, y_test),
        verbose=0
    )

    end = time.time()

    train_acc = history.history['accuracy'][-1]
    val_acc = history.history['val_accuracy'][-1]

    results.append({
        "Method": name,
        "Batch Size": batch_size,
        "Train Acc": round(train_acc, 4),
        "Test Acc": round(val_acc, 4),
        "Time (s)": round(end - start, 2)
    })

# ======================
# 5. Comparison Table
# ======================
df = pd.DataFrame(results)

print("\n\n===== FINAL COMPARISON TABLE =====")
print(df.sort_values(by="Test Acc", ascending=False).to_string(index=False))

/usr/local/lib/python3.12/dist-packages/jax/_src/cloud_tpu_init.py:86: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(


170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step

Running: Batch GD


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)



Running: SGD

Running: Mini-Batch GD

Running: Momentum

Running: Nesterov

Running: Adagrad

Running: RMSprop

Running: Adadelta

Running: Adam


===== FINAL COMPARISON TABLE =====
       Method  Batch Size  Train Acc  Test Acc  Time (s)
         Adam          64     0.4672    0.4651     68.99
     Nesterov          64     0.4970    0.4627     42.40
     Momentum          64     0.4775    0.4566     33.84
      Adagrad          64     0.4751    0.4374     46.76
      RMSprop          64     0.4559    0.4023     52.26
          SGD           1     0.3659    0.3799    780.72
Mini-Batch GD          64     0.4487    0.3681     25.72
     Adadelta          64     0.3093    0.3058     79.53
     Batch GD       50000     0.1664    0.1728     16.01
